-- MySQL Script generated by MySQL Workbench
-- 06/15/16 09:39:54
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sena_db
-- -----------------------------------------------------
-- マスタ関連
-- -----------------------------------------------------
-- Schema sena_secure_db
-- -----------------------------------------------------
-- ユーザー関連
CREATE SCHEMA IF NOT EXISTS `sena_secure_db` ;
USE `sena_secure_db` ;

-- -----------------------------------------------------
-- Table `sena_secure_db`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sena_secure_db`.`users` ;

CREATE TABLE IF NOT EXISTS `sena_secure_db`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ユーザーID',
  `account_id` VARCHAR(20) BINARY NOT NULL COMMENT 'アカウントID',
  `password` VARCHAR(45) BINARY NOT NULL COMMENT 'パスワード（暗号化）',
  `nickname` VARCHAR(20) NOT NULL COMMENT 'ニックネーム',
  `access_token` VARCHAR(128) BINARY NOT NULL COMMENT 'アクセストークン',
  `use_datetime` DATETIME NOT NULL COMMENT '利用日時',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `modified` DATETIME NOT NULL COMMENT '更新日時',
  `delete_flg` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '削除フラグ（1：削除、0：未削除）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'ユーザー';

CREATE INDEX `i_users1` ON `sena_secure_db`.`users` (`delete_flg` ASC, `access_token` ASC);

CREATE INDEX `i_users2` ON `sena_secure_db`.`users` (`delete_flg` ASC, `account_id` ASC, `password` ASC);

CREATE INDEX `i_users3` ON `sena_secure_db`.`users` (`delete_flg` ASC, `account_id` ASC);


-- -----------------------------------------------------
-- Table `sena_secure_db`.`account_stocks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sena_secure_db`.`account_stocks` ;

CREATE TABLE IF NOT EXISTS `sena_secure_db`.`account_stocks` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '口座銘柄ID',
  `users_id` BIGINT NOT NULL COMMENT 'ユーザーID',
  `acquisition_datetime` DATETIME NOT NULL COMMENT '取得日時',
  `stock_code` INT NOT NULL COMMENT '銘柄コード',
  `type` INT NOT NULL COMMENT '取引種別（1..国内株式、2..金額・株数指定取引、3..信用建玉（買建）、4..信用建玉（売建））',
  `closing_date` DATE NULL COMMENT '大引けを表す日付（null..取引中、日付..取引終了（終値）、PTS夜間取引は考慮しない）',
  `closing_flg` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '大引けを表すフラグ（1：大引け、0：取引中）',
  `amount` DECIMAL(25,10) NOT NULL COMMENT '保有株数（整数部：15桁、小数部：10桁）',
  `average_cost` DECIMAL(25,10) NOT NULL COMMENT '平均取得単価（整数部：15桁、小数部：10桁）',
  `current_value` DECIMAL(20,5) NOT NULL COMMENT '現在値（整数部：15桁、小数部：5桁）',
  `market_value` DECIMAL(25,10) NOT NULL COMMENT '時価評価額（「保有株数 * 現在値」で算出された値、整数部：15桁、小数部：10桁）',
  `profit_loss` DECIMAL(25,10) NOT NULL COMMENT '評価損益（「（保有株数 * 現在値） - （保有株数 * 平均取得単価）」で算出された値、整数部：15桁、小数部：10桁）',
  `profit_loss_rate` DECIMAL(10,2) NOT NULL COMMENT '損益率（「（評価損益 / （保有株数 * 現在値）） * 100」で算出された値、整数部：8桁、小数部：2桁）',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `modified` DATETIME NOT NULL COMMENT '更新日時',
  `delete_flg` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '削除フラグ（1：削除、0：未削除）',
  PRIMARY KEY (`id`, `users_id`))
ENGINE = InnoDB
COMMENT = '口座銘柄';

CREATE INDEX `fk_account_stocks_users_idx` ON `sena_secure_db`.`account_stocks` (`users_id` ASC);

CREATE INDEX `fk_account_stocks_stocks1_idx` ON `sena_secure_db`.`account_stocks` (`stock_code` ASC);

CREATE INDEX `i_account_stocks1` ON `sena_secure_db`.`account_stocks` (`delete_flg` ASC, `users_id` ASC, `closing_flg` ASC);


-- -----------------------------------------------------
-- Table `sena_secure_db`.`account_summaries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sena_secure_db`.`account_summaries` ;

CREATE TABLE IF NOT EXISTS `sena_secure_db`.`account_summaries` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '口座サマリーID',
  `users_id` BIGINT NOT NULL COMMENT 'ユーザーID',
  `acquisition_datetime` DATETIME NOT NULL COMMENT '取得日時',
  `closing_date` DATE NULL COMMENT '大引けを表す日付（null..取引中、日付..取引終了（終値）、PTS夜間取引は考慮しない）',
  `closing_flg` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '大引けを表すフラグ（1：大引け、0：取引中）',
  `free_margin` INT NULL COMMENT '信用建余力',
  `stock_purchased` INT NULL COMMENT '現引可能額',
  `initial_margin_cache` INT NULL COMMENT '委託保証金現金',
  `initial_margin_value` INT NULL COMMENT '代用有価証券評価額合計',
  `payment_expenses_total` INT NULL COMMENT '評価損・決済損益・支払諸経費等合計',
  `initial_margin` INT NULL COMMENT '実質保証金',
  `open_interest` INT NULL COMMENT '建代金合計',
  `maintenance_requirement` DECIMAL(10,2) NULL COMMENT '委託保証金率',
  `ref_maintenance_requirement` DECIMAL(10,2) NULL COMMENT '参考委託保証金率',
  `free_cache` INT NOT NULL COMMENT '買付余力',
  `free_cache_etc` INT NOT NULL COMMENT '現金残高等',
  `asset_value` DECIMAL(20,5) NOT NULL COMMENT '株式',
  `margin_profit_loss` INT NOT NULL COMMENT '建玉評価損益額',
  `account_balance` DECIMAL(20,5) NOT NULL COMMENT '計',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `modified` DATETIME NOT NULL COMMENT '更新日時',
  `delete_flg` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '削除フラグ（1：削除、0：未削除）',
  PRIMARY KEY (`id`, `users_id`))
ENGINE = InnoDB
COMMENT = '口座サマリー';

CREATE INDEX `fk_account_summaries_users1_idx` ON `sena_secure_db`.`account_summaries` (`users_id` ASC);

CREATE INDEX `i_account_summaries1` ON `sena_secure_db`.`account_summaries` (`delete_flg` ASC, `users_id` ASC, `closing_flg` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
