-- MySQL Script generated by MySQL Workbench
-- Sun Mar 12 00:53:53 2017
-- Model: sena_ERD    Version: sena-core-1.2.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sena_db
-- -----------------------------------------------------
-- マスタ関連
CREATE SCHEMA IF NOT EXISTS `sena_db` DEFAULT CHARACTER SET utf8mb4 ;
-- -----------------------------------------------------
-- Schema sena_secure_db
-- -----------------------------------------------------
-- ユーザー関連
USE `sena_db` ;

-- -----------------------------------------------------
-- Table `sena_db`.`stock_prices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sena_db`.`stock_prices` ;

CREATE TABLE IF NOT EXISTS `sena_db`.`stock_prices` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '株価ID',
  `date` DATE NOT NULL COMMENT '日付',
  `stock_code` INT NOT NULL COMMENT '銘柄コード',
  `opening_price` DECIMAL(20,5) NOT NULL COMMENT '始値	（整数部：15桁、小数部：5桁）',
  `high_price` DECIMAL(20,5) NOT NULL COMMENT '高値	（整数部：15桁、小数部：5桁）',
  `low_price` DECIMAL(20,5) NOT NULL COMMENT '安値	（整数部：15桁、小数部：5桁）',
  `closing_price` DECIMAL(20,5) NOT NULL COMMENT '終値	（整数部：15桁、小数部：5桁）',
  `turnover` DECIMAL(20,5) NOT NULL COMMENT '出来高	（整数部：15桁、小数部：5桁）',
  `adjusted_closing_price` DECIMAL(20,5) NOT NULL COMMENT '調整後終値	（分割実施前の終値を分割後の値に調整したもの、整数部：15桁、小数部：5桁）',
  `created` DATETIME NOT NULL COMMENT '作成日時',
  `modified` DATETIME NOT NULL COMMENT '更新日時',
  `delete_flg` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '削除フラグ	（1：削除、0：未削除）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '株価';

CREATE INDEX `fk_stock_prices_stocks1_idx` ON `sena_db`.`stock_prices` (`stock_code` ASC);

CREATE UNIQUE INDEX `uk_stock_prices` ON `sena_db`.`stock_prices` (`date` ASC, `stock_code` ASC);

CREATE INDEX `i_stock_prices1` ON `sena_db`.`stock_prices` (`date` ASC, `stock_code` ASC);

CREATE INDEX `i_stock_prices2` ON `sena_db`.`stock_prices` (`stock_code` ASC, `date` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
